name: Validate with HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Validate using hacs/action
        uses: hacs/action@main
        with:
          category: integration

      - name: Validate using hassfest
        uses: home-assistant/actions/hassfest@master
